#### general settings
name: Dual_Path_RNN
use_tb_logger: true
num_spks: 2
#### datasets
datasets:
  train:
    dataroot: 'Y:/CSC/dual-path-rnn/data'
    dataroot_csv: 'Y:/CSC/dual-path-rnn/data/train.csv'

  val:
    dataroot: 'Y:/CSC/dual-path-rnn/data'
    dataroot_csv: 'Y:/CSC/dual-path-rnn/data/test_full.csv'
  
  dataloader_setting:
    shuffle: true
    num_workers: 1  # per GPU
    batch_size: 1
  
  audio_setting:
    sample_rate: 8000
    chunk_size: 3
    

#### network structures
Dual_Path_RNN:
  in_channels: 256
  out_channels: 64 
  hidden_channels: 128
  kernel_size: 2
  rnn_type: LSTM
  norm: ln
  dropout: 0
  bidirectional: true
  num_layers: 6
  K: 250
  num_spks: 2

#### training settings: learning rate scheme, loss
train:
  epoch: 100
  early_stop: 10
  path: checkpoints
  gpuid: [0]
  distributed: true

#### Optimizer settings
optim:
  name: Adam   ### Adam, RMSprop, SGD
  lr: !!float 5e-4
  momentum: 0
  weight_decay: 0
  clip_norm: 5

#### scheduler settings
scheduler:
  min_lr: !!float 1e-8
  patience: 2
  factor: 0.5

#### Resume training settings
resume:
  state: true
  path: checkpoints/best.pt


#### logger
logger:
  name: DPCL
  path: checkpoints
  screen: false
  tofile: true
  tensorboard: true
  print_freq: 10